import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
'use client'
import { ApolloProvider, ApolloClient, InMemoryCache } from '@apollo/client'
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const client = new ApolloClient({
  uri: '/api/graphql',
  cache: new InMemoryCache(),
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ApolloProvider client={client}>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ApolloProvider>
  )
}